title: "DeuteroNoise – America's Cup Soundscapes"
description: "Quantifying underwater acoustic impacts during the 37th America's Cup in Barcelona."
theme: jekyll-theme-minimal
logo: /assets/logo.png
show_downloads: false